services:
  app:
    build: .
    container_name: evently-container-dev
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - postgres_dev
    networks:
      - evently-network

  postgres_dev:
    image: postgres:14-alpine
    container_name: evently-container
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - evently-network

networks:
  evently-network:
    driver: bridge